"""Project-wide pytest configuration."""

from pathlib import Path


def pytest_configure(config) -> None:
    """Keep pytest temporary files inside the project checkout.

    Some managed Windows environments deny access to the default user Temp
    directory. The directory is generated by pytest and ignored by Git.
    """
    config.option.basetemp = str(Path(config.rootpath) / ".pytest-tmp")
